[project]
name = "panopticon"
version = "0.1.0"
description = "Applied Machine Learning group project."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deepface>=0.0.100",
    "faiss-cpu>=1.8.0; sys_platform == 'darwin'",
    "faiss-gpu-cu12==1.14.1.post1; sys_platform == 'linux'",
    "numpy>=2.4.6",
    "opencv-python>=4.13.0.92",
    "pandas>=3.0.3",
    "psycopg[binary]>=3.3.4",
    "pydantic-settings>=2.14.1",
    "scipy>=1.17.1",
    "tensorflow>=2.16.0; sys_platform == 'darwin'",
    "tensorflow[and-cuda]>=2.21.0; sys_platform == 'linux'",
    "tf-keras>=2.21.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "ipywidgets>=8.1.8",
    "matplotlib>=3.10.9",
    "pytest>=9.0.3",
    "scikit-learn>=1.8.0",
    "tensorflow-docs>=2025.2.19.33219",
]

# Trick to make the project into a local package.
[build-system]
requires = ["uv-build<1.0.0"]
build-backend = "uv_build"
